backend #66 - S3 - Brakujace testy repo usera
grupa35/pz-backend pull request #38
Opened 2018-05-21 19:47 UTC by mystery-of-silence

2018-05-22 02:09 UTC, rotkom requested changes

2018-05-22 02:09 UTC, romic96 commented on src/test/java/pl/shopgen/models/UserRepositoryTest.java
> +public class UserRepositoryTest extends SimpleMongoRepositoryTest<User, UserRepository>{
brakuje adnotacji

2018-06-01 06:28 UTC, rotkom approved these changes

2018-06-01 06:57 UTC, WRup approved these changes

2018-06-01 06:59 UTC, merged